version: '3.8'
services:
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=challenge_clickidea
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
  